# Generated by Django 5.1.1 on 2024-11-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0011_initial'),
        ('schedule_form', '0002_alter_schedule_adopter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='adopter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.user'),
        ),
    ]
