# Generated by Django 5.1.1 on 2024-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_form', '0007_alter_schedule_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='reason_choices',
            field=models.CharField(choices=[('change_of_mind', 'Change of Mind'), ('financial_constraints', 'Financial Constraints'), ('found_other_pet_stores', 'Found other Pet Stores'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
