# Generated by Django 5.1.1 on 2024-11-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
