# Generated by Django 5.1.1 on 2024-10-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
        ('pet_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.user')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_listing.pet')),
            ],
        ),
    ]
