# Generated by Django 5.1.1 on 2024-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_form', '0004_schedule_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
