# Generated by Django 5.1.1 on 2024-11-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0015_pet_is_approved'),
        ('schedule_form', '0006_schedule_reason_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='pet_listing.pet'),
        ),
    ]
