# Generated by Django 5.1.1 on 2024-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0007_remove_pet_description_alter_pet_adoption_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='time_in_shelter',
            field=models.DateField(blank=True, null=True),
        ),
    ]
