# Generated by Django 5.1.1 on 2024-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0009_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('fish', 'Fish'), ('bird', 'Bird'), ('hamster', 'Hamster'), ('rabbit', 'Rabbit'), ('guinea_pig', 'Guinea Pig'), ('turtle', 'Turtle'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('frog', 'Frog'), ('parrot', 'Parrot'), ('chinchilla', 'Chinchilla'), ('ferret', 'Ferret'), ('hedgehog', 'Hedgehog'), ('horse', 'Horse'), ('goat', 'Goat')], max_length=20),
        ),
    ]
