# Generated by Django 5.1.1 on 2024-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0011_pet_is_adopted_pet_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
