# Generated by Django 5.1.1 on 2024-11-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0014_pet_is_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
