# Generated by Django 5.1.1 on 2024-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0002_remove_pet_type_pet_description_pet_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(max_length=50),
        ),
    ]
