# Generated by Django 5.1.1 on 2024-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0005_rename_image_pet_main_image_alter_pet_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
