# Generated by Django 5.1.1 on 2024-10-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0006_pet_adoption_fee_pet_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/main/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/gallery/'),
        ),
    ]
