# Generated by Django 5.1.1 on 2024-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0012_pet_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
