# Generated by Django 5.1.1 on 2024-11-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0011_initial'),
        ('request_form', '0004_alter_adoption_adopter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.user'),
        ),
    ]
