# Generated by Django 5.1.1 on 2024-11-05 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0009_alter_profile_user'),
        ('request_form', '0005_alter_adoption_adopter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile'),
        ),
    ]
