# Generated by Django 5.1.1 on 2024-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form', '0009_alter_adoption_reason_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='reason_choices',
            field=models.CharField(choices=[('duplicate_request', 'Duplicate Request'), ('not_picking_up', 'Not Picking Up Pet on Time'), ('overwhelmed_adopter', 'Overwhelmed Adopter'), ('ethical_safety_concerns', 'Ethical or Safety Concerns'), ('inability_to_meet_needs', 'Inability to Meet Pet’s Needs'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
    ]
