# Generated by Django 5.1.1 on 2024-10-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('request_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='adopter_id',
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.user'),
        ),
    ]
