# Generated by Django 5.1.1 on 2024-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form', '0006_alter_adoption_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
