# Generated by Django 5.1.1 on 2024-11-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_remove_user_groups_remove_user_is_staff_and_more'),
        ('profile_management', '0005_alter_profile_user'),
        ('request_form', '0004_alter_adoption_adopter'),
        ('schedule_form', '0002_alter_schedule_adopter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
