# Generated by Django 5.1.1 on 2024-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_message_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='No message attached', max_length=999),
        ),
    ]
